# **UFO Sightings Data Overview**
**Dataset files:** `scrubbed.csv`, `complete.csv`

This notebook performs a deep introductory examination of the dataset(s)
to understand:

- What fields exist?
- What are their data types?
- How complete or incomplete is the data?
- What is the temporal and geographic coverage?
- What are the statistical properties of key fields?
- Where are potential issues that will require cleaning/wrangling?

This overview will guide all subsequent:
- Data cleaning and wrangling
- Feature engineering
- Analysis notebooks
- Visualization design choices

### Necessary Imports and Installation

In [2]:
!pip install pandas numpy matplotlib seaborn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 200)

Requirement already satisfied: pandas in /home/momena/proj/ufo-sightings/.venv/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: numpy in /home/momena/proj/ufo-sightings/.venv/lib/python3.12/site-packages (2.3.5)
Requirement already satisfied: matplotlib in /home/momena/proj/ufo-sightings/.venv/lib/python3.12/site-packages (3.10.7)
Requirement already satisfied: seaborn in /home/momena/proj/ufo-sightings/.venv/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/momena/proj/ufo-sightings/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/momena/proj/ufo-sightings/.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/momena/proj/ufo-sightings/.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /home/momena/proj/ufo-sightings/.venv/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/momena/proj/ufo-sightings/.venv/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/momena/proj/ufo-sightings/.venv/lib/python3.12/site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/momena/proj/ufo-sightings/.venv/lib/python3.12/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /home/momena/proj/ufo-sightings/.venv/lib/python3.12/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /home/momena/proj/ufo-sightings/.venv/lib/python3.12/site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /home/momena/proj/ufo-sightings/.venv/lib/python3.12/site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: six>=1.5 in /home/momena/proj/ufo-sightings/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

### Load datasets: Scrubbed Dataset

In [ ]:
scrubbed = pd.read_csv('../raw/scrubbed.csv', engine='python', on_bad_lines='skip')
scrubbed.head()

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.941111
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.38421,-98.581082
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.916667
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.803611

### Basic Structure

In [4]:
scrubbed.shape
scrubbed.info()
scrubbed.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80332 entries, 0 to 80331
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   datetime              80332 non-null  object
 1   city                  80332 non-null  object
 2   state                 74535 non-null  object
 3   country               70662 non-null  object
 4   shape                 78400 non-null  object
 5   duration (seconds)    80332 non-null  object
 6   duration (hours/min)  80332 non-null  object
 7   comments              80317 non-null  object
 8   date posted           80332 non-null  object
 9   latitude              80332 non-null  object
 10  longitude             80332 non-null  float64
dtypes: float64(1), object(10)
memory usage: 6.7+ MB

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
count,80332,80332,74535,70662,78400,80332,80332,80317,80332,80332,80332.000000
unique,69586,19900,67,5,29,537,8349,79997,317,18445,NaN
top,7/4/2010 22:00,seattle,ca,us,light,300,5 minutes,Fireball,12/12/2009,47.6063889,NaN
freq,36,525,9655,65114,16565,8635,4716,11,1510,581,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-86.772885
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.697205
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-176.658056
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-112.073333
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.903611
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-78.755000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178.441900

In [8]:
# Missing Values
scrubbed.isna().sum().sort_values(ascending=False)

country                 9670
state                   5797
shape                   1932
comments                  15
datetime                   0
city                       0
duration (seconds)         0
duration (hours/min)       0
date posted                0
latitude                   0
longitude                  0
dtype: int64

In [9]:
# Date time field quality
scrubbed['datetime'].head(20)

0     10/10/1949 20:30
1     10/10/1949 21:00
2     10/10/1955 17:00
3     10/10/1956 21:00
4     10/10/1960 20:00
5     10/10/1961 19:00
6     10/10/1965 21:00
7     10/10/1965 23:45
8     10/10/1966 20:00
9     10/10/1966 21:00
10    10/10/1968 13:00
11    10/10/1968 19:00
12    10/10/1970 16:00
13    10/10/1970 19:00
14    10/10/1971 21:00
15    10/10/1972 19:00
16    10/10/1972 22:30
17    10/10/1973 19:00
18    10/10/1973 23:00
19    10/10/1974 19:30
Name: datetime, dtype: object

In [10]:
# Parsing datetime field
pd.to_datetime(scrubbed['datetime'], errors='coerce').isna().mean()

np.float64(0.008639147537718469)

In [13]:
# Geographic Fields
scrubbed[['city','state','country','latitude']].sample(20)

                      city state country    latitude
52396              plummer    id      us  47.3352778
62123            hillsdale    mi      us  41.9200000
45723       hendersonville    nc      us  35.3186111
18180              memphis    tn      us  35.1494444
37440             freeland    md      us  39.7047222
34359            claremore    ok      us  36.3125000
65847            las vegas    nv      us  36.1750000
76576               seward    ak      us  60.1041667
67249  washington&#44 d.c.    dc     NaN   38.907231
18906            lancaster    ca      us  34.6980556
56184              hornell    ny      us  42.3277778
74774             ruidsoso    nm     NaN   33.331749
3930              amarillo    tx      us  35.2219444
5242         camano island    wa     NaN   48.187056
316                augusta    ks      us  37.6866667
16140      manhattan beach    ca      us  33.8847222
73569            hillsboro    oh      us  39.2022222
33605              orlando    fl      us  28.5380556
46097         johns island    sc      us  32.7922222
24100             san jose    ca      us  37.3394444

In [14]:
# Shape Column values
scrubbed['shape'].value_counts(dropna=False)

shape
light        16565
triangle      7865
circle        7608
fireball      6208
other         5649
unknown       5584
sphere        5387
disk          5213
oval          3733
formation     2457
cigar         2057
changing      1962
NaN           1932
flash         1328
rectangle     1297
cylinder      1283
diamond       1178
chevron        952
egg            759
teardrop       750
cone           316
cross          233
delta            7
round            2
crescent         2
pyramid          1
flare            1
hexagon          1
dome             1
changed          1
Name: count, dtype: int64

In [15]:
# Comments Length Distribution
scrubbed['comments'].str.len().describe()

count    80317.000000
mean        82.949015
std         39.027215
min          1.000000
25%         50.000000
50%         79.000000
75%        120.000000
max        246.000000
Name: comments, dtype: float64

### Load datasets: Complete Dataset

In [16]:
complete = pd.read_csv('../raw/complete.csv', engine='python', on_bad_lines='skip')
complete.head()

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.941111
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.38421,-98.581082
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.916667
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.803611

### Basic Structure

In [18]:
complete.shape
complete.info()
complete.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88679 entries, 0 to 88678
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   datetime              88679 non-null  object
 1   city                  88679 non-null  object
 2   state                 81270 non-null  object
 3   country               76314 non-null  object
 4   shape                 85757 non-null  object
 5   duration (seconds)    88677 non-null  object
 6   duration (hours/min)  85660 non-null  object
 7   comments              88644 non-null  object
 8   date posted           88679 non-null  object
 9   latitude              88679 non-null  object
 10  longitude             88679 non-null  float64
dtypes: float64(1), object(10)
memory usage: 7.4+ MB

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
count,88679,88679,81270,76314,85757,88677,85660,88644,88679,88679,88679.000000
unique,76159,22018,68,5,29,546,9791,88283,317,19469,NaN
top,7/4/2010 22:00,seattle,ca,us,light,300,5 minutes,Fireball,12/12/2009,0,NaN
freq,36,570,10449,70293,17872,8796,4796,12,1624,1494,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-85.021836
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.421744
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-176.658056
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-112.073333
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.650000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.769738
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,178.441900

In [19]:
# Missing Values
complete.isna().sum().sort_values(ascending=False)

country                 12365
state                    7409
duration (hours/min)     3019
shape                    2922
comments                   35
duration (seconds)          2
datetime                    0
city                        0
date posted                 0
latitude                    0
longitude                   0
dtype: int64

In [20]:
# Date time field quality
complete['datetime'].head(20)

0     10/10/1949 20:30
1     10/10/1949 21:00
2     10/10/1955 17:00
3     10/10/1956 21:00
4     10/10/1960 20:00
5     10/10/1961 19:00
6     10/10/1965 21:00
7     10/10/1965 23:45
8     10/10/1966 20:00
9     10/10/1966 21:00
10    10/10/1968 13:00
11    10/10/1968 19:00
12    10/10/1970 16:00
13    10/10/1970 19:00
14    10/10/1971 21:00
15    10/10/1972 19:00
16    10/10/1972 22:30
17    10/10/1973 19:00
18    10/10/1973 23:00
19    10/10/1974 17:00
Name: datetime, dtype: object

In [21]:
complete[['city','state','country','latitude']].sample(20)

                              city state country    latitude
85185              simcoe (canada)    on      ca   42.833333
70836                   greenville    sc      us  34.8525000
44623            in-flight (texas)    tx     NaN   32.972579
12455  johannesburg (south africa)   NaN     NaN           0
18198        skegness (uk/england)   NaN      gb   53.133333
73908                      phoenix    az      us  33.4483333
44258                      corning    ca      us  39.9277778
50469                      big bay    mi      us  46.8158333
31805                   springdale    ar      us  36.1866667
83342            montreal (canada)    qc      ca        45.5
57862                     wildwood    nj      us  38.9916667
33116                    san diego    ca      us  32.7152778
44021           helsinki (finland)   NaN     NaN   60.173324
7758                       chemung    ny      us  42.0083333
4136                    janesville    wi      us  42.6827778
83494                      redding    ca      us  40.5866667
75011             leadville (near)    co      us  39.2508333
53838                   menlo park    ca      us  37.4538889
46663                   blackwater    mo      us  38.9802778
88628                 murfreesboro    tn      us  35.8455556

In [23]:
# Shape Column values
complete['shape'].value_counts(dropna=False)

shape
light        17872
triangle      8489
circle        8453
fireball      6562
unknown       6319
other         6247
disk          6005
sphere        5755
oval          4119
NaN           2922
formation     2657
cigar         2241
changing      2140
flash         1472
rectangle     1418
cylinder      1382
diamond       1308
chevron       1007
egg            845
teardrop       817
cone           367
cross          265
delta            8
round            2
crescent         2
pyramid          1
flare            1
hexagon          1
dome             1
changed          1
Name: count, dtype: int64

In [24]:
# Comments Length Distribution
complete['comments'].str.len().describe()

count    88644.000000
mean        83.180497
std         39.323617
min          1.000000
25%         50.000000
50%         79.000000
75%        121.000000
max        246.000000
Name: comments, dtype: float64